Banco.create(banco_id: "0156", moneda: 1,nombre: "100%BANCO")
Banco.create(banco_id: "0196", moneda: 1,nombre: "ABN AMRO BANK")
Banco.create(banco_id: "0172", moneda: 1,nombre: "BANCAMIGA BANCO MICROFINANCIERO, C.A.")
Banco.create(banco_id: "0171", moneda: 1,nombre: "BANCO ACTIVO BANCO COMERCIAL, C.A.")
Banco.create(banco_id: "0166", moneda: 1,nombre: "BANCO AGRICOLA")
Banco.create(banco_id: "0175", moneda: 1,nombre: "BANCO BICENTENARIO")
Banco.create(banco_id: "0128", moneda: 1,nombre: "BANCO CARONI, C.A. BANCO UNIVERSAL")
Banco.create(banco_id: "0164", moneda: 1,nombre: "BANCO DE DESARROLLO DEL MICROEMPRESARIO")
Banco.create(banco_id: "0102", moneda: 1,nombre: "BANCO DE VENEZUELA S.A.I.C.A.")
Banco.create(banco_id: "0114", moneda: 1,nombre: "BANCO DEL CARIBE C.A.")
Banco.create(banco_id: "0149", moneda: 1,nombre: "BANCO DEL PUEBLO SOBERANO C.A.")
Banco.create(banco_id: "0163", moneda: 1,nombre: "BANCO DEL TESORO")
Banco.create(banco_id: "0176", moneda: 1,nombre: "BANCO ESPIRITO SANTO, S.A.")
Banco.create(banco_id: "0115", moneda: 1,nombre: "BANCO EXTERIOR C.A.")
Banco.create(banco_id: "0003", moneda: 1,nombre: "BANCO INDUSTRIAL DE VENEZUELA.")
Banco.create(banco_id: "0173", moneda: 1,nombre: "BANCO INTERNACIONAL DE DESARROLLO, C.A.")
Banco.create(banco_id: "0105", moneda: 1,nombre: "BANCO MERCANTIL C.A.")
Banco.create(banco_id: "0191", moneda: 1,nombre: "BANCO NACIONAL DE CREDITO")
Banco.create(banco_id: "0116", moneda: 1,nombre: "BANCO OCCIDENTAL DE DESCUENTO.")
Banco.create(banco_id: "0138", moneda: 1,nombre: "BANCO PLAZA")
Banco.create(banco_id: "0108", moneda: 1,nombre: "BANCO PROVINCIAL BBVA")
Banco.create(banco_id: "0104", moneda: 1,nombre: "BANCO VENEZOLANO DE CREDITO S.A.")
Banco.create(banco_id: "0168", moneda: 1,nombre: "BANCRECER S.A. BANCO DE DESARROLLO")
Banco.create(banco_id: "0134", moneda: 1,nombre: "BANESCO BANCO UNIVERSAL")
Banco.create(banco_id: "0177", moneda: 1,nombre: "BANFANB")
Banco.create(banco_id: "0146", moneda: 1,nombre: "BANGENTE")
Banco.create(banco_id: "0174", moneda: 1,nombre: "BANPLUS BANCO COMERCIAL C.A")
Banco.create(banco_id: "0190", moneda: 1,nombre: "CITIBANK.")
Banco.create(banco_id: "0121", moneda: 1,nombre: "CORP BANCA.")
Banco.create(banco_id: "0157", moneda: 1,nombre: "DELSUR BANCO UNIVERSAL")
Banco.create(banco_id: "0151", moneda: 1,nombre: "FONDO COMUN")
Banco.create(banco_id: "0601", moneda: 1,nombre: "INSTITUTO MUNICIPAL DE CR&#201;DITO POPULAR")
Banco.create(banco_id: "0169", moneda: 1,nombre: "MIBANCO BANCO DE DESARROLLO, C.A.")
Banco.create(banco_id: "0137", moneda: 1,nombre: "SOFITASA")
Banco.create(banco_id: "BOFA", moneda: 2,nombre: "BANK OF AMERICA (USA)")
Banco.create(banco_id: "COMM", moneda: 2,nombre: "COMMERCE BANK (USA)")
Banco.create(banco_id: "CITI", moneda: 2,nombre: "CITI BANK (USA)")
Banco.create(banco_id: "CHAS", moneda: 2,nombre: "CHASE (USA)")
Banco.create(banco_id: "WELL", moneda: 2,nombre: "WELLS FARGO (USA)")
Banco.create(banco_id: "BANP", moneda: 2,nombre: "BANESCO (PANAMA)")
Banco.create(banco_id: "MERP", moneda: 2,nombre: "MERCANTIL (PANAMA)")
Banco.create(banco_id: "HSBCP", moneda: 2,nombre: "BANISTMO (PANAMA)")
