# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ce533009e07b7fd33596162d58abcb6935041d6e1751445e17fdbfbc3fc101c07eed4bb4028bf96b167217cf48453160500299aa7c2a0c5944eb9b5ee0ad51b

test:
  secret_key_base: 857ed45e82ffcbbcd9e105c35c0f971a3d56cd86c0dc0922e642bef78eb228f49c1679db095b75d659ec957307e8e7fd3ec29973181673d92658da6e96bf14f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 065db9f857765e599fd2334a9eeedf1210d7c6ec240eda5dcfb2cd6049df622ee9b76d86f19989b1acf9a97109b1f0587a3537799bcfbc4350185470f5fc7a54
